ARM template update
SumoLogic/sumologic-azure-function pull request #76
Opened 2024-01-29 11:49 UTC by priyansh-sumo

- Git Action

2024-01-29 16:39 UTC, himanshu219 requested changes
1. uncomment the  git actions for metrics arm template
2. There are some warnings related to api versions in the git checks for arm ttk

2024-02-01 07:13 UTC, himanshu219 commented on .github/workflows/arm-template-test.yml
> +          rm -rf arm-ttk
why do we need to do rm -rf arm-ttk ?

2024-02-01 09:17 UTC, priyansh-sumo commented on .github/workflows/arm-template-test.yml
> +          shopt -s extglob
removed

2024-02-01 10:08 UTC, priyansh-sumo commented on .github/workflows/arm-template-test.yml
> +          rm -rf arm-ttk
updated with metrix logic.

2024-02-01 10:45 UTC, himanshu219 approved these changes

2024-02-01 10:45 UTC, merged